import { useEffect } from "react";
import { motion } from "framer-motion";
import { useNavigate } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

const Terms = () => {
  const navigate = useNavigate();

  useEffect(() => {
    document.title = "Terms of Service — Aethel Mirror";
  }, []);

  return (
    <div className="min-h-screen bg-background text-foreground px-5 py-8 max-w-2xl mx-auto">
      <button onClick={() => navigate(-1)} className="flex items-center gap-2 text-muted-foreground hover:text-foreground mb-8 transition-colors">
        <ArrowLeft className="w-4 h-4" /> Back
      </button>

      <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
        <h1 className="font-display text-2xl text-primary mb-2">Terms of Service</h1>
        <p className="text-muted-foreground text-sm mb-8">Last updated: 2 April 2026</p>

        <div className="space-y-6 font-body text-sm text-foreground/80 leading-relaxed">
          <section>
            <h2 className="font-display text-lg text-foreground mb-2">1. Age Requirement</h2>
            <p>You must be 18 years of age or older to use Aethel Mirror. By creating an account, you confirm that you meet this requirement.</p>
          </section>

          <section>
            <h2 className="font-display text-lg text-foreground mb-2">2. Nature of the Service</h2>
            <p>Aethel Mirror is a decision clarity tool that synthesises astrology, Human Design, numerology, Gene Keys, and Destiny Matrix into reflective guidance. Readings are generated by artificial intelligence and are for personal reflection purposes only.</p>
            <p className="mt-2"><strong className="text-foreground">Important:</strong> This service does not constitute professional medical, psychological, financial, legal, or any other form of professional advice. You should always consult qualified professionals for matters relating to your health, mental wellbeing, finances, or legal situation.</p>
          </section>

          <section>
            <h2 className="font-display text-lg text-foreground mb-2">3. Subscriptions & Billing</h2>
            <p>Aethel Mirror offers a free tier with limited monthly readings. Paid subscriptions (Mirror and Mirror Pro) are billed monthly via Stripe.</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li><strong className="text-foreground">Free tier:</strong> 3 readings per calendar month. No payment required.</li>
              <li><strong className="text-foreground">Mirror:</strong> Unlimited readings, full decision journal, and pattern analysis.</li>
              <li><strong className="text-foreground">Mirror Pro:</strong> Everything in Mirror plus personalised 30-day transit calendar and branded share cards.</li>
            </ul>
            <p className="mt-2">You may cancel your subscription at any time through the customer portal accessible from the Settings screen. Upon cancellation, you retain access to your paid tier until the end of your current billing period. No refunds are provided for partial months.</p>
          </section>

          <section>
            <h2 className="font-display text-lg text-foreground mb-2">4. Intellectual Property</h2>
            <p><strong className="text-foreground">Your data:</strong> You own your personal data, including questions you submit, journal entries, and outcome notes. You may export or delete all of your data at any time from the Settings screen.</p>
            <p className="mt-2"><strong className="text-foreground">The platform:</strong> Aethel Mirror, including its name, design, algorithms, and curated content library, is the intellectual property of Aethel and may not be reproduced, reverse-engineered, or redistributed without written permission.</p>
          </section>

          <section>
            <h2 className="font-display text-lg text-foreground mb-2">5. User Content & Anonymous Sharing</h2>
            <p>When you opt in to anonymous sharing (via the consent checkbox when logging an outcome), your outcome data may be used in aggregated, anonymised form to improve the service and display on our Evidence page. No personally identifiable information is ever shared publicly.</p>
          </section>

          <section>
            <h2 className="font-display text-lg text-foreground mb-2">6. Limitation of Liability</h2>
            <p>Aethel Mirror and its creators accept no liability for any decisions you make based on readings or guidance provided by the app. All AI-generated content is provided "as is" without warranties of any kind. All actions taken as a result of using this service are taken at your own risk and discretion.</p>
            <p className="mt-2">In no event shall Aethel's total liability exceed the amount paid by you for the service in the preceding 12 months.</p>
          </section>

          <section>
            <h2 className="font-display text-lg text-foreground mb-2">7. Crisis & Safety</h2>
            <p>Aethel Mirror includes automated crisis detection. If our system detects signals of acute emotional distress, you will be shown crisis resources instead of a reading. This is not a substitute for professional crisis support — if you are in danger, please contact emergency services immediately.</p>
          </section>

          <section>
            <h2 className="font-display text-lg text-foreground mb-2">8. Account Termination</h2>
            <p>We reserve the right to suspend or terminate accounts that violate these terms, engage in abusive behaviour, or attempt to exploit the service. You may delete your account and all associated data at any time from the Settings screen.</p>
          </section>

          <section>
            <h2 className="font-display text-lg text-foreground mb-2">9. Governing Law</h2>
            <p>These terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.</p>
          </section>

          <section>
            <h2 className="font-display text-lg text-foreground mb-2">10. Contact</h2>
            <p>For questions about these terms, contact: <a href="mailto:legal@aethelmirror.com" className="text-primary hover:underline">legal@aethelmirror.com</a></p>
          </section>
        </div>
      </motion.div>
    </div>
  );
};

export default Terms;
